### ISSUE TITLE
Support no_std

### ISSUE THREAD

**Issue by chipsenkbeil** [chipsenkbeil/memtable-rs#1]
Through two features: `std` and `alloc`. Have `std` enabled by default.

### MemTable, FixedRowMemTable, and FixedColumnMemTable

- In the case where `alloc` is enabled, we pull in [hashbrown](https://crates.io/crates/hashbrown) to provide the hashmap impl needed for `MemTable`
- In the case where `std` is enabled, we use the standard library's hashmap
- In case where neither `alloc` nor `std` is enabled, we exclude this export

### FixedTable

- Doesn't need anything special as using const generics to define array sizes, no dynamic allocation

### CSV

- In the case of the absence of `std` (how ???), we pull in [csv-core](https://crates.io/crates/csv-core)
- In the case where `std` is enabled, we pull in [csv](https://crates.io/crates/csv)

### Cells

- Doesn't need anything special

**Comment by chipsenkbeil** [comment]
Dependencies:

```toml
# default-features = false to get rid of libc
csv-core = { version = "0.1.10", default-features = false, optional = true }
hashbrown = { version = "0.11.2", optional = true }
```
